# Copyright (c) 2018-2022 The MobileCoin Foundation
apiVersion: v1
kind: Service
metadata:
  name: mobilecoind-grpc
  labels:
    {{- include "mobilecoind.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: mobilecoind
    {{- include "mobilecoind.selectorLabels" . | nindent 4 }}
  ports:
  - name: mobilecoind-grpc
    port: 80
    targetPort: mobilecoind-grpc
