# Copyright (c) 2018-2022 The MobileCoin Foundation
# Keep this one for backwards compatibility with older tests.
apiVersion: v1
kind: Service
metadata:
  name: mobilecoind
  labels:
    {{- include "mobilecoind.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: mobilecoind
    {{- include "mobilecoind.selectorLabels" . | nindent 4 }}
  ports:
  - name: grpc
    port: 3229
    targetPort: grpc
