[package]
name = "mc-util-grpc-token-generator"
version = "1.2.0-pre2"
authors = ["MobileCoin"]
edition = "2018"

[[bin]]
name = "mc-util-grpc-token-generator"
path = "src/bin/main.rs"

[dependencies]
mc-common = { path = "../../common", features = ["std"] }
mc-util-grpc = { path = "../grpc" }

hex = "0.4"
percent-encoding = "2.1.0"
structopt = "0.3"
