[build]
target = "../../../x86_64-mobilecoin-none-sgx.json"
# target = "x86_64-mobilecoin-none-sgx"

[unstable]
build-std = ["core", "alloc"]

[env]
RUST_MBEDTLS_TARGET = "x86_64-unknown-linux-gnu"
PKG_CONFIG_ALLOW_CROSS = "1"