# Copyright (c) 2018-2022 The MobileCoin Foundation
#
# MobileCoin Core projects - Dispatch (manual) Job - Run integration tests in a development namespace.

name: mobilecoin-dispatch-dev-test

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "Target Namespace"
        type: string
        required: true
      ingest_color:
        description: "Fog Ingest blue/green"
        type: string
        required: true
        default: blue
      fog_distribution:
        description: "Run fog-distribution test"
        type: boolean
        required: false
        default: true
      fog_test_client_v0:
        description: "Run fog-test-client test"
        type: boolean
        required: false
        default: true
      fog_test_client_v2:
        description: "Run fog-test-client test"
        type: boolean
        required: false
        default: true
      mobilecoind_grpc_integration:
        description: "Run mobilecoind-grpc integration test"
        type: boolean
        required: false
        default: true
      mobilecoind_json_integration:
        description: "Run mobilecoind-json integration test"
        type: boolean
        required: false
        default: true
      minting:
        description: "Run minting setup tests"
        type: boolean
        required: false
        default: true
      mint_auditor:
        description: "Run mint-auditor tests"
        type: boolean
        required: false
        default: true
      drain_account:
        description: "Run drain_account.py to move coin from initial keys to fog keys accounts"
        type: boolean
        required: false
        default: true

jobs:
  test:
    uses: ./.github/workflows/mobilecoin-workflow-dev-test.yaml
    with:
      namespace: ${{ github.event.inputs.namespace }}
      ingest_color: ${{ github.event.inputs.ingest_color }}
      fog_distribution: ${{ github.event.inputs.fog_distribution == 'true' && 'true' || 'false' }}
      fog_test_client_v0: ${{ github.event.inputs.fog_test_client_v0 == 'true' && 'true' || 'false' }}
      fog_test_client_v2: ${{ github.event.inputs.fog_test_client_v2 == 'true' && 'true' || 'false' }}
      mobilecoind_grpc_integration: ${{ github.event.inputs.mobilecoind_grpc_integration == 'true' && 'true' || 'false' }}
      mobilecoind_json_integration: ${{ github.event.inputs.mobilecoind_json_integration == 'true' && 'true' || 'false' }}
      minting: ${{ github.event.inputs.minting == 'true' && 'true' || 'false' }}
      mint_auditor: ${{ github.event.inputs.mint_auditor == 'true' && 'true' || 'false' }}
      drain_account: ${{ github.event.inputs.drain_account == 'true' && 'true' || 'false' }}
    secrets:
      RANCHER_CLUSTER: ${{ secrets.RANCHER_CLUSTER }}
      RANCHER_URL: ${{ secrets.RANCHER_URL }}
      RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
      FOG_REPORT_SIGNING_CA_CERT: ${{ secrets.DEV_FOG_REPORT_SIGNING_CA_CERT }}
