# Copyright (c) 2018-2022 The MobileCoin Foundation
#
# MobileCoin Core projects - Dispatch (manual) Job - Update consensus nodes in a development namespace.

name: mobilecoin-dispatch-dev-update-consensus

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "Target Namespace"
        type: string
        required: true
      version:
        description: "Chart Version"
        type: string
        required: true
      block_version:
        description: "Block Version"
        type: string
        required: true
        default: '0'
      chart_repo:
        description: "Chart Repo URL"
        type: string
        required: true
        default: https://harbor.mobilecoin.com/chartrepo/mobilecoinfoundation-public
jobs:
  update-consensus-block-version:
    uses: ./.github/workflows/mobilecoin-workflow-dev-update-consensus.yaml
    with:
      namespace: ${{ github.event.inputs.namespace }}
      block_version: "${{ github.event.inputs.block_version }}"
      version: ${{ github.event.inputs.version }}
      chart_repo: ${{ github.event.inputs.chart_repo }}
    secrets:
      RANCHER_CLUSTER: ${{ secrets.RANCHER_CLUSTER }}
      RANCHER_URL: ${{ secrets.RANCHER_URL }}
      RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
      LEDGER_AWS_ACCESS_KEY_ID: ${{ secrets.DEV_LEDGER_AWS_ACCESS_KEY_ID }}
      LEDGER_AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_LEDGER_AWS_SECRET_ACCESS_KEY }}
      IAS_KEY: ${{ secrets.DEV_IAS_KEY }}
      IAS_SPID: ${{ secrets.DEV_IAS_SPID }}
      FOG_REPORT_SIGNING_CERT: ${{ secrets.DEV_FOG_REPORT_SIGNING_CERT }}
      FOG_REPORT_SIGNING_CERT_KEY: ${{ secrets.DEV_FOG_REPORT_SIGNING_CERT_KEY }}
